### ISSUE TITLE
Enable dependabot for github actions

### ISSUE THREAD

**Issue by chohner** [digitalservicebund/ris-ui#57]
With a few lines of yaml you can ensure your github actions stay up-to-date:

```
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
```

reference: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
